# Generated by Django 5.1 on 2024-09-12 12:18

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("address", models.TextField(max_length=15000)),
                ("commission_title", models.CharField(max_length=250)),
                ("commission_idea", models.TextField(max_length=100000)),
                (
                    "canvas_size",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                ("deadline_date", models.DateField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "framing_options",
                    models.CharField(
                        choices=[
                            ("n/a", "N/A"),
                            ("behind glass", "Behind Glass"),
                            ("tray frame", "Tray Frame"),
                        ],
                        default="n/a",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="commission.commission",
                    ),
                ),
            ],
        ),
    ]
