# Generated by Django 5.1 on 2024-09-12 12:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Past_Commission_Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=250)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
