# Generated by Django 5.1 on 2024-09-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0002_past_commission_images"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Past_Commission_Images", new_name="Past_Commission_Image",
        ),
    ]
