# Generated by Django 5.1 on 2024-09-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0003_rename_past_commission_images_past_commission_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
