# Generated by Django 5.1 on 2025-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0004_commission_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="medium",
            field=models.CharField(
                choices=[
                    ("canvas", "Canvas"),
                    ("digital file", "Digital File"),
                    ("mural", "Mural"),
                    ("3d", "3D"),
                    ("wholesale", "Wholesale"),
                    ("other", "Other"),
                ],
                default="canvas",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commission",
            name="other_info",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
