# Generated by Django 5.1 on 2024-08-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0002_product_is_sold_out_product_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=250)),
                ("shipping_address", models.TextField(max_length=15000)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=7)),
                ("date_ordered", models.DateTimeField(auto_now_add=True)),
                ("shipped", models.BooleanField(default=False)),
                ("date_shipped", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_full_name", models.CharField(max_length=255)),
                ("shipping_email", models.CharField(max_length=255)),
                ("shipping_address1", models.CharField(max_length=255)),
                (
                    "shipping_address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("shipping_city", models.CharField(max_length=255)),
                ("shipping_region", models.CharField(max_length=255)),
                ("shipping_postcode", models.CharField(max_length=255)),
                ("shipping_country", models.CharField(max_length=255)),
            ],
            options={"verbose_name_plural": "Shipping Address",},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
