# Generated by Django 5.1 on 2024-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False),
        ),
    ]
