# Generated by Django 5.1 on 2024-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_order_invoice_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
