# Generated by Django 5.1 on 2024-09-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_order_payer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
