# Generated by Django 5.1 on 2024-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_order_payment_intent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank="True",
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                ],
                default="unpaid",
                max_length=10,
                null="True",
            ),
            preserve_default="True",
        ),
    ]
