# Generated by Django 5.1 on 2024-09-10 12:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                ("body", models.TextField(blank=True, default="", null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "image1",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image1"
                    ),
                ),
                ("caption1", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image2",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image2"
                    ),
                ),
                ("caption2", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image3",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image3"
                    ),
                ),
                ("caption3", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image4",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image4"
                    ),
                ),
                ("caption4", models.CharField(blank=True, max_length=200, null=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
