# Generated by Django 5.1 on 2024-09-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_quantity_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_size",
            field=models.BooleanField(default=False),
        ),
    ]
