# Generated by Django 5.1 on 2024-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_is_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_size",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
