# Generated by Django 5.1 on 2024-09-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_product_is_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size",
                to="shop.product",
            ),
        ),
    ]
