# Generated by Django 5.1 on 2024-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_size_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="is_sold_out",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
