# Generated by Django 5.1 on 2024-10-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_size_is_sold_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_on_shelf",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
