# Generated by Django 5.1 on 2024-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_is_on_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
    ]
