# Generated by Django 5.1 on 2024-10-12 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_front_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="front_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
